# Dogma constants.
ATTRIBUTE_CPU = 50
ATTRIBUTE_PG = 30

ATTRIBUTE_LOWSLOTS = 12
ATTRIBUTE_MEDSLOTS = 13
ATTRIBUTE_HIGHSLOTS = 14
ATTRIBUTE_RIGSLOTS = 1137
ATTRIBUTE_SUBSYSTEMS = 1367

ATTRIBUTE_MISSILESLOTS = 101
ATTRIBUTE_TURRETSLOTS = 102

